In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [1]:
import numpy as np


In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
x = np.array([2,3,5,1,2,4])
print(x)
print('total elements =>',x.size)
print('dimension wise elements=>',x.shape)
print('dimension count',x.ndim)

[2 3 5 1 2 4]
total elements => 6
dimension wise elements=> (6,)
dimension count 1


In [5]:
y = np.array([[2,3,5],[3,2,1]])
print(y)
print('total elements =>',y.size)
print('dimension wise elements=>',y.shape)
print('dimension count',y.ndim)

[[2 3 5]
 [3 2 1]]
total elements => 6
dimension wise elements=> (2, 3)
dimension count 2


In [6]:
x= [1,2,3]
z = np.array([[x,x,x],[x,x,x],[x,x,x]])
print('shape',z.shape)
print(z)

shape (3, 3, 3)
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]]


In [7]:
d = np.arange(-10,11,.5)
d.shape

(42,)

In [8]:
d.reshape(6,7)

array([[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
       [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
       [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ],
       [  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
       [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]])

In [9]:
d.reshape(2,3,7)

array([[[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
        [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
        [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ]],

       [[  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
        [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
        [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]]])

In [10]:
a = np.linspace(1, 1000, 11)
a

array([   1. ,  100.9,  200.8,  300.7,  400.6,  500.5,  600.4,  700.3,
        800.2,  900.1, 1000. ])

In [11]:
d = np.random.randint(1,6,(10,10))

In [12]:
print(d)

[[1 3 3 5 1 4 5 5 1 2]
 [1 5 5 3 5 5 3 2 5 2]
 [1 5 2 2 4 1 2 1 1 2]
 [4 2 2 2 2 3 2 4 1 3]
 [5 5 2 4 3 1 3 2 4 2]
 [2 3 4 3 2 4 4 3 4 2]
 [4 3 1 2 3 5 4 4 3 1]
 [1 2 4 3 2 2 1 5 4 4]
 [4 4 4 5 5 4 5 3 5 5]
 [5 1 2 2 4 1 5 1 4 2]]


In [13]:
d[-1]

array([5, 1, 2, 2, 4, 1, 5, 1, 4, 2])

In [14]:
d[0,0] # d[0][0]

1

In [15]:
d[3,5]

3

In [16]:
d[:, 0] # all rows of column idx 0

array([1, 1, 1, 4, 5, 2, 4, 1, 4, 5])

In [17]:
d[:, -3]

array([5, 2, 1, 4, 2, 3, 4, 5, 3, 1])

In [18]:
d[:5, 2] # first five rows of column idx 2

array([3, 5, 2, 2, 2])

In [19]:
d[:5, :5] # ?

array([[1, 3, 3, 5, 1],
       [1, 5, 5, 3, 5],
       [1, 5, 2, 2, 4],
       [4, 2, 2, 2, 2],
       [5, 5, 2, 4, 3]])

In [20]:
x = np.random.randint(1, 10, (3,3))
y = np.random.randint(1, 10, (3,3))
print(x,'\n', y)

[[4 4 6]
 [9 7 2]
 [2 2 8]] 
 [[9 4 7]
 [8 8 1]
 [4 7 4]]


In [21]:
x + y

array([[13,  8, 13],
       [17, 15,  3],
       [ 6,  9, 12]])

In [22]:
x - y

array([[-5,  0, -1],
       [ 1, -1,  1],
       [-2, -5,  4]])

In [23]:
x + 10

array([[14, 14, 16],
       [19, 17, 12],
       [12, 12, 18]])

In [24]:
x - 10

array([[-6, -6, -4],
       [-1, -3, -8],
       [-8, -8, -2]])

In [25]:
x * 10

array([[40, 40, 60],
       [90, 70, 20],
       [20, 20, 80]])

In [26]:
np.dot(x,y)

array([[ 92,  90,  56],
       [145, 106,  78],
       [ 66,  80,  48]])

In [27]:
np.matmul(x,y)

array([[ 92,  90,  56],
       [145, 106,  78],
       [ 66,  80,  48]])

In [28]:
np.multiply(x,y)

array([[36, 16, 42],
       [72, 56,  2],
       [ 8, 14, 32]])

In [29]:
x * y

array([[36, 16, 42],
       [72, 56,  2],
       [ 8, 14, 32]])

In [30]:
np.cross(x,y)

array([[  4,  26, -20],
       [ -9,   7,  16],
       [-48,  24,   6]])

In [31]:
np.hstack([x,y])

array([[4, 4, 6, 9, 4, 7],
       [9, 7, 2, 8, 8, 1],
       [2, 2, 8, 4, 7, 4]])

In [32]:
np.vstack([x,y])

array([[4, 4, 6],
       [9, 7, 2],
       [2, 2, 8],
       [9, 4, 7],
       [8, 8, 1],
       [4, 7, 4]])

In [33]:
np.append(x,y,axis=0)

array([[4, 4, 6],
       [9, 7, 2],
       [2, 2, 8],
       [9, 4, 7],
       [8, 8, 1],
       [4, 7, 4]])

In [34]:
x.max()

9

In [36]:
x.max(axis=0)

array([9, 7, 8])

In [37]:
x.min(axis=1)

array([4, 2, 2])

In [38]:
x.flatten()

array([4, 4, 6, 9, 7, 2, 2, 2, 8])

In [39]:
d[d > 3] # boolean filter

array([5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 5, 5, 4, 4, 4, 4, 4, 4, 4,
       5, 4, 4, 4, 5, 4, 4, 4, 4, 4, 5, 5, 4, 5, 5, 5, 5, 4, 5, 4])

In [40]:
d[d==1] # give all the ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])